//Author: Harshil Parmar.
package player;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ConnectException;
import java.net.Socket;
import javax.swing.JButton;


public class Player extends javax.swing.JFrame {

    private final int port = 9001;

    private final String host = "localhost";

    private Socket socket = null;

    //Initialize data input stream
    private DataInputStream dataInputStreamFromServer = null;
    private DataOutputStream dataOutputStreamToServer = null;

    private String tocken = null;

    //Initialize button array
    private JButton[] buttons = new JButton[9];

    /**
     * Creates new form Player
     */
    public Player() {
        initComponents();

        buttons[0] = jButton1;
        buttons[1] = jButton2;
        buttons[2] = jButton3;
        buttons[3] = jButton4;
        buttons[4] = jButton5;
        buttons[5] = jButton6;
        buttons[6] = jButton7;
        buttons[7] = jButton8;
        buttons[8] = jButton9;

        try {
            socket = new Socket(host, port);

            dataInputStreamFromServer = new DataInputStream(socket.getInputStream());
            dataOutputStreamToServer = new DataOutputStream(socket.getOutputStream());

            new ReadFromServer().start();

        } catch (ConnectException c_ex) {
            txtBoxMessage.setText("Server is Offline.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textBoxPanel = new javax.swing.JPanel();
        txtBoxMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-Tac-Toe Game");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        buttonPanel.setBackground(new java.awt.Color(0, 0, 0));
        buttonPanel.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setEnabled(false);
        jButton7.setName("7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton7);
        jButton7.getAccessibleContext().setAccessibleName("button7");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setEnabled(false);
        jButton8.setName("8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton8);
        jButton8.getAccessibleContext().setAccessibleName("button8");

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setEnabled(false);
        jButton9.setName("9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton9);
        jButton9.getAccessibleContext().setAccessibleName("button9");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setEnabled(false);
        jButton4.setName("4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton4);
        jButton4.getAccessibleContext().setAccessibleName("button4");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setEnabled(false);
        jButton5.setName("5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton5);
        jButton5.getAccessibleContext().setAccessibleName("button5");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setEnabled(false);
        jButton6.setName("6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton6);
        jButton6.getAccessibleContext().setAccessibleName("button6");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setName("1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton1);
        jButton1.getAccessibleContext().setAccessibleName("button1");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setName("2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton2);
        jButton2.getAccessibleContext().setAccessibleName("button2");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setName("3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerfomed(evt);
            }
        });
        buttonPanel.add(jButton3);
        jButton3.getAccessibleContext().setAccessibleName("button3");

        textBoxPanel.setLayout(new java.awt.GridLayout(1, 0));

        txtBoxMessage.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtBoxMessage.setEnabled(false);
        textBoxPanel.add(txtBoxMessage);
        txtBoxMessage.getAccessibleContext().setAccessibleName("messageBox");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(textBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerfomed
        try {
            dataOutputStreamToServer.writeUTF(tocken + ":" + ((JButton) evt.getSource()).getName());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_actionPerfomed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player().setVisible(true);
            }
        });
    }

    private class ReadFromServer extends Thread {

        public void run() {
            while (true) {
                try {
                    String[] messageFromServer = dataInputStreamFromServer.readUTF().split(":");
                    
                    //receive token from server                    
                    if (messageFromServer[0].equals("tocken")) {
                        tocken = messageFromServer[1];
                    }

                    //receive text message from server                    
                    if (messageFromServer[0].equals("txtMessage")) {
                        txtBoxMessage.setText(messageFromServer[1]);
                    }

                    //Enable buttons                    
                    if (messageFromServer[0].equals("enableAll")) {
                        for (JButton button : buttons) {
                            button.setEnabled(true);
                        }
                    }

                    
                    //enable particular buttons that are not selected                    
                    if (messageFromServer[0].equals("enable")) {
                        for (JButton button : buttons) {
                            if (button.getText().equals("")) {
                                button.setEnabled(true);
                            }
                        }
                    }
                    
                    //disable all button in game
                    if (messageFromServer[0].equals("disableAll")) {
                        for (JButton button : buttons) {
                            button.setEnabled(false);
                        }
                    }

                    //disable button and change sign on button                    
                    if (messageFromServer[0].equals("X") || messageFromServer[0].equals("O")) {
                        buttons[Integer.parseInt(messageFromServer[1]) - 1].setEnabled(false);
                        buttons[(Integer.parseInt(messageFromServer[1])) - 1].setText(messageFromServer[0]);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel textBoxPanel;
    private javax.swing.JTextField txtBoxMessage;
    // End of variables declaration//GEN-END:variables
}
